stages:
  - deploy

deploy_backend:
  stage: deploy
  only:
    - main
  script:
    - cd /var/www/tvdl/backend
    - git pull
    - npm install
    - npx prisma migrate deploy
    - pm2 restart tvdl-backend

seed_db:
  stage: deploy
  when: manual
  only:
    - main
  needs: ["deploy_backend"]
  script:
    - cd /var/www/tvdl/backend && node scripts/seed.js

deploy_frontend:
  stage: deploy
  only:
    - main
  needs: ["deploy_backend"]
  script:
    - cd /var/www/tvdl/frontend
    - git pull
    - npm install
    - npm run build
